### ISSUE TITLE
Copying drawn objects to an overlay

### ISSUE THREAD

**Issue by SwagMuffinMcYoloPants** [angular-ui/ui-leaflet-draw#6]
I have a use case where I have to be able to have multiple overlays with the ability to draw/edit on them similar to what PhotoShop does.  I currently have a directive that lets you select an overlay.  When you switch from Overlay A to Overlay B, I currently want to copy each layer from the draw FeatureGroup to Overlay A and then clear out the draw FeatureGroup to populate it with the contents of Overlay B.  Am I making this more complex than it should be?  I feel like there should be an easier way.  I tried just moving the drawn objects straight to the overlays but doing that makes the edit controls not work because it requires an edit object with a feature group.

**Comment by nmccready** [comment]
leaflet-draw itself and this directive are not that flexible in the since of working out of the box. Now it is very flexible once you start overriding / extending leaflet-draw interfaces low level. After that you need to make custom directives and services. I have another for of doing exactly this that I was planning to open source at some point. 

Anyway, please ask your question on stack overflow. I mentioned the above for people with special use cases to give them some direction on where to go.
